server:
  port: 9527

spring:
  application:
    name: cloud-gateway #以微服务注册进 consul 或 nacos 服务列表内
  cloud:
    consul: #配置consul地址
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}
    #  网关配置
    gateway:
      routes:
        - id: pay_routh1 #pay_routh1                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-payment-service           #  uri: http://localhost:8001                #匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/get/**              # 断言，路径相匹配的进行路由
            - After=2024-03-20T14:34:36.152600+08:00[Asia/Shanghai]
            - Agony=gold


        - id: pay_routh2 #pay_routh2                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-payment-service #          uri: http://localhost:8001                #匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/info/**              # 断言，路径相匹配的进行路由

        - id: pay_routh3 #pay_routh3
          uri: lb://cloud-payment-service                #匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/filter/**              # 断言，路径相匹配的进行路由
          #            - Path=/aaa/{segment}
          filters:
            - AddRequestHeader=X-Request-agony1,agonyValue1  # 请求头kv，若一头含有多参则重写一行设置
            - AddRequestHeader=X-Request-agony2,agonyValue2
            - AddRequestParameter=customerId,9527001 # 新增请求参数Parameter：k ，v
            - RemoveRequestParameter=customerName   # 删除url请求参数customerName，你传递过来也是null
      #            - SetPath=/pay/gateway/{segment}
      #  全局过滤器
      default-filters:
        - AddRequestHeader=AgonyName,Agony